*-- STRINGS.H
*-- Include this file where needed for localization
*-- purposes

*-- Messagebox Titles
#DEFINE ERRORTITLE_LOC       "Terjadi Kesalahan"
#DEFINE TITLE_LOC            "Sistem Penggajian Pegawai Negeri Sipil"

*-- Toolbar names
#DEFINE TB_FORMDESIGNER_LOC  "Form Designer"
#DEFINE TB_STANDARD_LOC      "Standard"
#DEFINE TB_LAYOUT_LOC        "Layout"
#DEFINE TB_QUERY_LOC		 "Query Designer"
#DEFINE TB_VIEWDESIGNER_LOC  "View Designer"
#DEFINE TB_COLORPALETTE_LOC  "Color Palette"
#DEFINE TB_FORMCONTROLS_LOC  "Form Controls"
#DEFINE TB_DATADESIGNER_LOC  "Database Designer"
#DEFINE TB_REPODESIGNER_LOC  "Report Designer"
#DEFINE TB_REPOCONTROLS_LOC  "Report Controls"
#DEFINE TB_PRINTPREVIEW_LOC  "Print Preview"
#DEFINE WIN_COMMAND_LOC		 "Command"			&& Command Window

*-- Messagebox Messages
#DEFINE FILENOTEXIST_LOC	"File tidak ditemukan: "
#DEFINE BADPASSWORD_LOC		"Password Anda salah. Ulangi lagi."
#DEFINE BADNAME_LOC			"Nama tidak tercatat."
#DEFINE SAVECHANGES_LOC		"Simpan Perubahan Data Ini ?"
#DEFINE ASKDELETE_LOC		"Anda yakin mau hapus data ini?"
#DEFINE TAGNOTFOUND_LOC		"Index tag tidak ditemukan."
#DEFINE REPORTNOTFOUND_LOC	"File Report tidak ditemukan."
#DEFINE PRINTERNOTREADY_LOC	"Printer tidak siap."
#DEFINE NORECSMATCHED_LOC	"Tidak ada records yang memenuhi kriteria."
#DEFINE DELETEREC_LOC		"Anda yakin mau hapus record ini?"
#DEFINE DELETEWARN_LOC      "Peringatan Penghapusan Data"
#DEFINE NOTHINGTOPRINT_LOC  "Tidak ada yang tercetak"
#DEFINE PASSWORDEMPTY_LOC	"Password baru tidak bisa kosong."
#DEFINE PSWDNOTCNFRM_LOC    "Tidak bisa konfirmasi password baru. Coba ulangi lagi."
#DEFINE NOPSWDENTERED_LOC	"Anda belum memasukkan password lama. Anda ingin melanjutkan?"
#DEFINE FILESAVEDAS_LOC		"File disimpan dengan nama "
#DEFINE VALIDATING_LOC      "Validating ..."
#DEFINE PRINTING_LOC        "Printing ..."
#DEFINE VIEWCODEPRINT_LOC	"This report may be lengthy. Do you want to continue?"
#DEFINE VIEWCSDTYPRINT_LOC  "This report may be lengthy. Do you want to continue?"
#DEFINE METHOD_LOC          "Metode: "
#DEFINE LINENUM_LOC			"Baris: "
#DEFINE CANNOTQUIT_LOC      "Tidak bisa keluar dari Visual FoxPro tanpa melalui GajiPns."
#DEFINE ADDNEWREC_LOC		"Ini adalah record terakhir. Anda ingin menanbah record baru?"
#DEFINE ENTERADDMODE_LOC    "Tidak ada record di file. Pilih mode 'Tambah Data'."
#DEFINE CLASSBROWERR_LOC	"Anda tidak berwenang menggunakan Library ini."

*-- Trigger error messages
#DEFINE INSERTTRIGFAIL_LOC  "Insert trigger failed!"
#DEFINE UPDATETRIGFAIL_LOC  "Update trigger failed!"
#DEFINE DELETETRIGFAIL_LOC  "Delete trigger failed!"
#DEFINE DELGOLONGAN_LOC		"Golongan tercatat di orders. Tidak dapat dihapus!"
#DEFINE DELSATKERJA_LOC		"Satuan Kerja tercatat di orders. Tidak dapat dihapus!"
#DEFINE DELUNITKERJA_LOC	"Unit Kerja tercatat di orders. Tidak dapat dihapus!"
#DEFINE EXIST_LOC           "Data telah tercatat dalam file ini ....."
#DEFINE NOTFOUND_LOC        "Data tidak tercatat dalam file ini ....."
#DEFINE NOTEMPTY_LOC        "Data harus diisi, tidak bisa dikosongkan  ....."

*-- Other strings
#DEFINE ADDPICTURE_LOC      "Tambah Gambar"
#DEFINE CHANGEPICTURE_LOC	"Ubah Gambar/Photo"
#DEFINE SELECTBUTTON_LOC    "Select"
#DEFINE VERSION_LOC			"1.1"
#DEFINE COPYRIGHT_LOC		"Copyright (c) 2004 MSM"
#DEFINE RIGHTSRSRVD_LOC		"(r) All rights reserved"
#DEFINE ADDITEM_LOC			"Tambah Item"
#DEFINE INSERTITEM_LOC	    "Sisipkan Item"
#DEFINE REMOVEITEM_LOC      "Hapus Item"
#DEFINE INFSAVED_LOC        "Data telah disimpan."
#DEFINE REINDEXING_LOC      "Reindexing: "
#DEFINE DONE_LOC            "Selesai dilakukan....."
#DEFINE LOWERNOTFOUND_LOC	" tidak ditemukan."
#DEFINE ABOUT_LOC			"Mengenai "
#DEFINE VERSIONLABEL_LOC    "Versi "
#DEFINE USERNAME_LOC        ""
#DEFINE USERCORP_LOC        ""
